### ISSUE TITLE
El evento está vendido

### ISSUE THREAD

**Issue by ralodev** [gomez-julian/salle-strapi-backend#1]
Cómo va a ganar ese wey

**Comment by gomez-julian** [comment]
De seguro su papá es el men que se durmió en nuestra exposición.
😑😑😐

**Comment by ralodev** [comment]
igual y sí 💅 
![5](https://user-images.githubusercontent.com/93017723/192913804-4cdf2df8-c414-4b68-b99d-16b5ef0198f9.PNG)
